### ISSUE TITLE
没有适配高版本的

### ISSUE THREAD

**Issue by DreamClimb** [smashinggit/Study#1]
高版本的没有适配权限

**Comment by IOCloudFly** [comment]
加一下就好了
在gradle里面引入一个权限管理
implementation 'com.hjq:xxpermissions:5.2'
在MainActivity里面加入
`XXPermissions.with(this)`
                .permission(com.hjq.permissions.Permission.CAMERA)
                .permission(*com.hjq.permissions.Permission.Group.STORAGE)
                .permission(com.hjq.permissions.Permission.RECORD_AUDIO)
                .request(object : OnPermission {
                    override fun hasPermission(granted: List<String>, isAll: Boolean) {

                    }

                    override fun noPermission(denied: List<String>, quick: Boolean) {
                        if (quick) {
                            Toast.makeText(this@MainActivity, "被永久拒绝，请手动设置权限", Toast.LENGTH_SHORT).show()
                            XXPermissions.gotoPermissionSettings(this@MainActivity)
                        } else {
                            Toast.makeText(this@MainActivity, "获取权限失败", Toast.LENGTH_SHORT).show()
                        }
                    }
                })`

**Comment by smashinggit** [comment]
已修改
