### ISSUE TITLE
拍摄完第一次，再拍摄一次会crash，见图

### ISSUE THREAD

**Issue by w13897215200** [smashinggit/Study#8]
![image](https://user-images.githubusercontent.com/16714931/100950351-1bc86480-3547-11eb-8515-66c23d5dced8.png)

**Comment by jaxlifu** [comment]
![image](https://user-images.githubusercontent.com/10626921/129318553-6614b87c-fa67-4793-94af-9639b57e3011.png)

这里错误的将 image.close() 写成了 ImageReader.close()

**Comment by smashinggit** [comment]
代码已修改上传，感谢
